name: my_first_application
description: "my_first_application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  english_words: ^4.0.0

  provider: ^6.1.1
  json_annotation: ^4.8.1

  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  json_serializable: ^6.7.1
  build_runner: ^2.4.8

  flutter_launcher_icons: "^0.13.1"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/robotoMono/regular.ttf
        - asset: assets/fonts/robotoMono/regular_italic.ttf
          style: italic
        - asset: assets/fonts/robotoMono/medium.ttf
          weight: 500
        - asset: assets/fonts/robotoMono/bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/bold.ttf
          weight: 700
        - asset: assets/fonts/lato/bold_italic.ttf
          weight: 700
          style: italic

    - family: Parisienne
      fonts:
        - asset: assets/fonts/parisienne/regular.ttf

    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm_sans/regular.ttf
          weight: 400

    - family: Lufga
      fonts:
        - asset: assets/fonts/lufga/medium.ttf
          weight: 500
        - asset: assets/fonts/lufga/bold.ttf
          weight: 600